[template]
keys = [
    "/upstream",
]
owner = "nginx"
mode = "0644"
src = "app-nginx.tmpl"
dest = "/etc/nginx/sites-enabled/app.conf"
check_cmd = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "/usr/sbin/service nginx reload"